server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: none;
  application:
    name: temporal-closer-look
  curriculum:
    task-queue: app
  temporal:
    test-server:
      enabled: false
    workers:
      - task-queue: TRANSFER_RECEIPTS_TASK_QUEUE
        # fullName: your-worker-fullName # unique fullName of the Worker. If not specified, Task Queue is used as the Worker fullName.
        workflow-classes:
          - temporal.inventory.receiptsusecase.TransferReceiptWorkflowImpl
        activity-beans:
          - save-status-activity
          - geo-validate-data-activity
          - geo-transform-model-activity
          - geo-enrichment-activity
          - embassy-transform-validate-data-activity
          - embassy-acknowledge-data-activity
    namespace: default # https://docs.temporal.io/cloud/#temporal-cloud-namespace-id
    connection:
      target: 127.0.0.1:7233

# (Note following configuration are not set by default but serve more as reference)
#    workers:
#      - task-queue: DemoTaskQueue
#        capacity:
#          max-concurrent-workflow-task-pollers: 6
#          max-concurrent-activity-task-pollers: 6
#          max-concurrent-workflow-task-executors: 6
#          max-concurrent-activity-task-executors: 6
#          max-concurrent-local-activity-task-executors: 6
#        rate-limits:
#          max-worker-activities-per-second: 3
#          max-task-queue-activities-per-second: 3
#    workflow-cache:
#      max-instances: 10
#      max-threads: 10
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}